application:
  port: 8000
email_client:
  base_url: "localhost"
  sender_email: "miguel.iglesias@dimeder.com"
  authorization_token: "secret"
database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  database_name: newsletter